# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tree', 'Tree'), ('grass', 'Grass'), ('rock', 'Rock'), ('water', 'Water')], max_length=100, verbose_name='Type')),
                ('position_x', models.PositiveIntegerField(verbose_name='Position X')),
                ('position_y', models.PositiveIntegerField(verbose_name='Position Y')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('width', models.PositiveIntegerField(verbose_name='Width')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='map.Map'),
        ),
    ]
